name: "CD (Entrega Continua): Main Workflow"

env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches: ["main"]

  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run navigate to Nextjs dir
        run: cd Estudos\NextJs\CI_CD_com_GitHub_Actions

      - name: Run install dependaces
        run: yarn install
      
      - name: Run Deploy
        run: yarn deploy:prod