name: "CI (Integração Continua): Main Workflow"

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

  
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run navigate to CI&CD dir
        run: cd ./Nextjs/'CI&CD com GitHub Actions' 
      
      - name: Run Linter
        run: yarn lint
