name: "CI (Integração Continua): Main Workflow"

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

  
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run navigate to Nextjs dir
        run: cd Estudos/NextJs/CI_CD_com_GitHub_Actions

      - name: Run install dependaces
        run: yarn install
      
      - name: Run Linter
        run: yarn lint
