name: "CI (Integração Continua): Main Workflow"


env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

  
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run navigate to Nextjs dir
        run: cd Estudos/NextJs/Ci-Cd-github-actions

      - name: Run install dependaces
        run: yarn install
      
      - name: Run Linter
        run: yarn lint
  
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run navigate to Nextjs dir
        run: cd Estudos/NextJs/Ci-Cd-github-actions

      - name: Run install dependaces
        run: yarn install

      - name: Run deploy
        run:  yarn deploy:preview
  
  test_e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.18.2
          cache: 'yarn'
      - name: Cypress
        uses: cypress-io/github-actions@v4
        with:
          browser: chrome

      - name: Run navigate to Nextjs dir
        run: cd Estudos/NextJs/Ci-Cd-github-actions

      - name: Run install dependaces
        run: yarn install

      - name: Run cypress
        run:  yarn test:e2e
